# Generated by Django 2.1.5 on 2019-03-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name='Code')),
                ('color_name', models.CharField(max_length=45, verbose_name='Color name')),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True, verbose_name='Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('output_standard', models.DecimalField(decimal_places=4, default=0, help_text='Jumlah output yang dikeluarkan oleh formula produksi, sesuai satuan dalam stock', max_digits=14, verbose_name='Standard output formula')),
            ],
            options={
                'verbose_name': '1.8. Formula',
                'verbose_name_plural': '1.8. Daftar Formula',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True, verbose_name='Price')),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BillOfMaterial', verbose_name='BoM')),
            ],
            options={
                'verbose_name': '1.8.1 Rincian Formula',
                'verbose_name_plural': '1.8.1 Daftar Rincian Formula',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
            ],
            options={
                'verbose_name': '1.1. Customer',
                'verbose_name_plural': '1.1. Daftar Customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
            ],
            options={
                'verbose_name': '1.2. Kategori Customer',
                'verbose_name_plural': '1.2. Daftar Kategori Customer',
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Quantity')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='First edited')),
            ],
            options={
                'verbose_name': '2.1. Penyesuaian / Pemutihan Stock',
                'verbose_name_plural': '2.1. Penyesuaian / Pemutihan Stock',
            },
        ),
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('type', models.CharField(choices=[('TTD', 'Raw material'), ('BT', 'Finished good'), ('CON', 'Consumable')], max_length=3, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Price')),
                ('initial', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Saldo Awal')),
            ],
            options={
                'verbose_name': '1.5. Stock Barang',
                'verbose_name_plural': '1.5. Daftar Stock Barang',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Price')),
                ('bom_output_standard', models.DecimalField(decimal_places=4, default=0, help_text='Jumlah output yang dikeluarkan oleh formula produksi, sesuai satuan dalam stock', max_digits=14, verbose_name='Standard output formula')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('on_going', 'Dalam proses'), ('pending', 'Pending'), ('done', 'Selesai')], default='pending', max_length=8, verbose_name='Status')),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.BillOfMaterial', verbose_name='BoM')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': '1.9. Produksi',
                'verbose_name_plural': '1.9. Produksi',
            },
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Price')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.InventoryItems', verbose_name='Item')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Manufacture', verbose_name='Manufacture process')),
            ],
            options={
                'verbose_name': '2.0. Penggunaan Barang',
                'verbose_name_plural': '2.0. Daftar Penggunaan Barang',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note', models.CharField(blank=True, max_length=45, null=True, verbose_name='Delivery note')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Price')),
                ('status', models.CharField(choices=[('receipt', 'Receipt'), ('return', 'Return')], max_length=7, verbose_name='Status')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Item')),
            ],
            options={
                'verbose_name': '1.6. Pembelian Barang',
                'verbose_name_plural': '1.6. Pembelian Barang',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_order', models.CharField(blank=True, max_length=45, null=True, verbose_name='Delivery order')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('sent', 'Delivery'), ('return', 'Return')], max_length=6, verbose_name='Status')),
                ('jo_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='JO number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Customer', verbose_name='Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Item')),
            ],
            options={
                'verbose_name': '1.7. Pengiriman Barang [ Finished Good ]',
                'verbose_name_plural': '1.7. Pengiriman Barang [ Finisehd Good ]',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
            ],
            options={
                'verbose_name': '1.3. Supplier',
                'verbose_name_plural': '1.3. Daftar Supplier',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
            ],
            options={
                'verbose_name': '1.4. Unit Satuan',
                'verbose_name_plural': '1.4. Unit Satuan',
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='productusage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='billofmaterialdetails',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='billofmaterialdetails',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='customer_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.CustomerCategory', verbose_name='Customer category'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Product'),
        ),
    ]
