# Generated by Django 2.1.5 on 2019-01-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '1.3. Supplier', 'verbose_name_plural': '1.3. Supplier List'},
        ),
    ]
