# Generated by Django 2.1.5 on 2019-01-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20190130_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name='Code')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
                ('type', models.CharField(choices=[('TTD', 'Raw material'), ('BT', 'Finished good')], max_length=3, verbose_name='Type')),
            ],
            options={
                'verbose_name': '1.5. Inventory',
                'verbose_name_plural': '1.5. Invetories',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note', models.CharField(blank=True, max_length=45, null=True, verbose_name='Delivery note')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('status', models.CharField(choices=[('receipt', 'Receipt'), ('return', 'Return')], max_length=7, verbose_name='Status')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': '1.6. Stock Input/Ouput [ Raw Material ]',
                'verbose_name_plural': '1.6. Stock Input/Ouput [ Raw Material ]',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_order', models.CharField(blank=True, max_length=45, null=True, verbose_name='Delivery order')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('sent', 'Delivery'), ('return', 'Return')], max_length=6, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Customer', verbose_name='Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Item')),
            ],
            options={
                'verbose_name': '1.7. Stock Input/Ouput [ Finished Good ]',
                'verbose_name_plural': '1.7. Stock Input/Ouput [ Finished Good ]',
            },
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name')),
            ],
            options={
                'verbose_name': '1.4. Unit Measurement',
                'verbose_name_plural': '1.4. Unit Measurements',
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
    ]
