# Generated by Django 2.1.5 on 2019-01-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20190130_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name='Code')),
                ('color_name', models.CharField(max_length=45, verbose_name='Color name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Customer', verbose_name='Customer')),
                ('customer_caterory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.CustomerCategory', verbose_name='Customer category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Product')),
            ],
            options={
                'verbose_name': '1.8. Bill of Material [ Formula ]',
                'verbose_name_plural': '1.8. Bill of Material [ Formula ]',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.BillOfMaterial', verbose_name='BoM')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.UnitMeasurement', verbose_name='Unit')),
            ],
            options={
                'verbose_name': '1.9. BoM Detail [ Formula Detail ]',
                'verbose_name_plural': '1.9. BoM Detail [ Formula Detail ]',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datetime')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.BillOfMaterial', verbose_name='BoM')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.Customer', verbose_name='Customer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.UnitMeasurement', verbose_name='Unit')),
            ],
            options={
                'verbose_name': '2.0. Manufacture [ Production ]',
                'verbose_name_plural': '1.9. Manufacture [ Production ]',
            },
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='production.InventoryItems', verbose_name='Item')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Manufacture', verbose_name='Manufacture process')),
            ],
            options={
                'verbose_name': '2.1. Product Usage',
                'verbose_name_plural': '2.1. Product Usage List',
            },
        ),
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'verbose_name': '1.6. Stock [ Raw Material ]', 'verbose_name_plural': '1.6. Stock [ Raw Material ]'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': '1.7. Stock [ Finished Good ]', 'verbose_name_plural': '1.7. Stock [ Finished Good ]'},
        ),
    ]
