# Generated by Django 2.1.5 on 2019-01-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20190130_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='customer_caterory',
            new_name='customer_category',
        ),
    ]
