# Generated by Django 2.1.5 on 2019-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20190130_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
