# Generated by Django 2.1.5 on 2019-01-31 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_manufacture_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='production.UnitMeasurement', verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='type',
            field=models.CharField(choices=[('TTD', 'Raw material'), ('BT', 'Finished good'), ('CONS', 'Consumable')], max_length=3, verbose_name='Type'),
        ),
    ]
