# Generated by Django 2.1.5 on 2019-02-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20190131_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems',
            name='type',
            field=models.CharField(choices=[('TTD', 'Raw material'), ('BT', 'Finished good'), ('CON', 'Consumable')], max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='bill_of_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.BillOfMaterial', verbose_name='BoM'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.InventoryItems', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.UnitMeasurement', verbose_name='Unit'),
        ),
    ]
