# Generated by Django 2.1.5 on 2019-02-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20190201_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitems',
            options={'verbose_name': '1.5. Items', 'verbose_name_plural': '1.5. Items'},
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Quantity'),
        ),
    ]
