# Generated by Django 2.1.5 on 2019-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20190201_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='billofmaterialdetails',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='billofmaterialdetails',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Quantity'),
        ),
    ]
