# Generated by Django 2.1.5 on 2019-02-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20190201_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterial',
            options={'verbose_name': '1.8. Formula', 'verbose_name_plural': '1.8. Daftar Formula'},
        ),
        migrations.AlterModelOptions(
            name='billofmaterialdetails',
            options={'verbose_name': '1.9. Rincian Formula', 'verbose_name_plural': '1.9. Daftar Rincian Formula'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '1.1. Customer', 'verbose_name_plural': '1.1. Daftar Customer'},
        ),
        migrations.AlterModelOptions(
            name='customercategory',
            options={'verbose_name': '1.2. Kategori Customer', 'verbose_name_plural': '1.2. Daftar Kategori Customer'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitems',
            options={'verbose_name': '1.5. Stock Barang', 'verbose_name_plural': '1.5. Daftar Stock Barang'},
        ),
        migrations.AlterModelOptions(
            name='manufacture',
            options={'verbose_name': '1.9. Produksi', 'verbose_name_plural': '1.9. Produksi'},
        ),
        migrations.AlterModelOptions(
            name='productusage',
            options={'verbose_name': '2.0. Penggunaan Barang', 'verbose_name_plural': '2.0. Daftar Penggunaan Barang'},
        ),
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'verbose_name': '1.6. Pembelian Barang', 'verbose_name_plural': '1.6. Pembelian Barang'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': '1.7. Pengiriman Barang [ Finished Good ]', 'verbose_name_plural': '1.7. Pengiriman Barang [ Finisehd Good ]'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '1.3. Supplier', 'verbose_name_plural': '1.3. Daftar Supplier'},
        ),
        migrations.AlterModelOptions(
            name='unitmeasurement',
            options={'verbose_name': '1.4. Unit Satuan', 'verbose_name_plural': '1.4. Unit Satuan'},
        ),
        migrations.AddField(
            model_name='manufacture',
            name='status',
            field=models.CharField(choices=[('on_going', 'Dalam proses'), ('pending', 'Pending'), ('done', 'Selesai')], default='pending', max_length=8, verbose_name='Status'),
        ),
    ]
