# Generated by Django 2.1.5 on 2019-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20190213_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='available',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
