# Generated by Django 2.1.5 on 2019-02-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20190215_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='billofmaterialdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=14, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Price'),
        ),
    ]
