# Generated by Django 2.1.5 on 2019-02-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20190215_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Quantity')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
                ('first_created', models.DateTimeField(auto_now_add=True, verbose_name='First edited')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.InventoryItems', verbose_name='Item')),
            ],
            options={
                'verbose_name': '2.1. Penyesuaian / Pemutihan Stock',
                'verbose_name_plural': '2.1. Penyesuaian / Pemutihan Stock',
            },
        ),
    ]
