# Generated by Django 2.1.5 on 2019-02-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_inventoryadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='initial',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Saldo Awal'),
        ),
        migrations.AlterField(
            model_name='inventoryitems',
            name='available',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Tersedia'),
        ),
    ]
