# Generated by Django 2.1.5 on 2019-02-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_auto_20190219_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitems',
            name='available',
        ),
    ]
