# Generated by Django 2.1.5 on 2019-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_remove_inventoryitems_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='jo_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='JO number'),
        ),
    ]
